# Generated by Django 5.0 on 2023-12-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.FileField(default='', upload_to='media/'),
        ),
    ]
